### ISSUE TITLE
Numbers immediately following Qualifiers fail to parse the relaxed semver parser

### ISSUE THREAD

**Issue by Geolykt** [Rebirth-Project/version-comparator#1]
These versions are rather common, e.g.:
- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api/5.11.0-M2
- https://mvnrepository.com/artifact/org.clojure/clojure/1.12.0-alpha12
- https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api/6.1.0-M2
- https://mvnrepository.com/artifact/jakarta.ws.rs/jakarta.ws.rs-api/4.0.0-M2
- https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib/2.0.0-RC3
- https://mvnrepository.com/artifact/org.mozilla/rhino/1.7.14-RC1
- https://mvnrepository.com/artifact/org.beanshell/bsh/2.0b5
- and much more

**Comment by patton73** [comment]
Ok this is a bug.  Thanks a lot for pointing this out.
But this is not a valid version for the relaxed parser  https://mvnrepository.com/artifact/org.beanshell/bsh/2.0b5.
It lacks for major.minor.patch structure, And it lacks also a . or a - before the qualifier.
